# fly.toml app configuration file generated for grotto-beasts-app-test on 2023-06-12T14:42:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grotto-beasts-app-test"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
